apiVersion: apps/v1
kind: Deployment
metadata:
  name: vat-operator
  namespace: vat-operator
spec:
  template:
    spec:
      containers:
        - name: operator
          env:
            - name: VAT_CLUSTER_NAME
              value: k3s-remote
            - name: VAT_OPERATOR_RUNTIME_PROFILE
              value: k3s
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: vat-operator-node-agent
  namespace: vat-operator
spec:
  template:
    spec:
      containers:
        - name: node-agent
          env:
            - name: VAT_CLUSTER_NAME
              value: k3s-remote
            - name: VAT_OPERATOR_RUNTIME_PROFILE
              value: k3s
            - name: VAT_CONTAINERD_SOCKET_PATH
              value: /host/run/k3s/containerd/containerd.sock
            - name: VAT_KUBELET_ROOT_PATH
              value: /host/var/lib/kubelet
            - name: VAT_STATIC_POD_MANIFEST_PATH
              value: /host/var/lib/rancher/k3s/server/manifests
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vat-scanner-worker
  namespace: vat-operator
spec:
  template:
    spec:
      containers:
        - name: scanner
          env:
            - name: VAT_CLUSTER_NAME
              value: k3s-remote
