apiVersion: v1
kind: ServiceAccount
metadata:
  name: vat-operator
  namespace: {{ include "vat-operator.namespace" . }}
  labels:
    app.kubernetes.io/name: vat-operator
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.scanner.serviceAccountName }}
  namespace: {{ include "vat-operator.namespace" . }}
  labels:
    app.kubernetes.io/name: vat-operator-scanner
