apiVersion: v1
kind: ServiceAccount
metadata:
  name: vat-operator
  namespace: vat-operator
  labels:
    app.kubernetes.io/name: vat-operator
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vat-operator-scanner
  namespace: vat-operator
  labels:
    app.kubernetes.io/name: vat-operator-scanner
