apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
generators:
  - ksops-generator.yaml
images:
  - name: vat-backend
    newName: harbor.automatedhass.com/library/vat/backend
    newTag: latest
  - name: vat-frontend
    newName: harbor.automatedhass.com/library/vat/frontend
    newTag: latest
patches:
  - path: patch-frontend-lb.yaml
