apiVersion: v1
kind: Secret
metadata:
  name: vat-egress-proxy
  namespace: vat
type: Opaque
stringData:
  HTTP_PROXY: http://vat-egress-proxy.vat.svc.cluster.local.:3128
  HTTPS_PROXY: http://vat-egress-proxy.vat.svc.cluster.local.:3128
