apiVersion: v1
kind: Secret
metadata:
    name: vat-runtime
    namespace: vat
    annotations:
        argocd.argoproj.io/sync-wave: "-1"
type: Opaque
stringData:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:s6g4OJOpBJn/HgaCfzLg0DWSFo0ggG5SXC3z,iv:OWhmpyW6z79BWIVoMO9dQI5vb5uURwEDSRKP7EUWhbQ=,tag:6ryITgdCJr+LLA1OYpZyTQ==,type:str]
    VAT_DATABASE_URL: ENC[AES256_GCM,data:s8VorgMUntt9MVdl8NVLUwnnWwRfq2EJ7iq9MYVVLCqHWcc2EJlV3R8uxrmhsK3l7nVE7cTTOVZCQpCR9Z0xvvietk38Ug==,iv:te0BEhRjEgl+CeHH8kjlnE8DxtVGCBpj8q6gdb0+dwY=,tag:uckz72mifYKPMEKwn83dgw==,type:str]
    VAT_CELERY_BROKER_URL: ENC[AES256_GCM,data:lzz4rgAUriLCV2cF4wQ6/oN8ulhG,iv:8DKW4xJdXXxNwqAyzDAFE3lLcVMg02Tkg1uhY5NljB8=,tag:Pr9uYEeRxL+BZ9NmcTasmg==,type:str]
    VAT_SECRET_KEY: ENC[AES256_GCM,data:KsbG3GtrFJiQIspV5OQzGTQTi7l1fe0VkZAnQVlyxfCbMbcfentdEz0u,iv:tkVY/3hGSK+JzpESP2WMp52kwj9Ml2FV5zVwTZLIlH4=,tag:TUWsdHYLlfWQyWab/4zeeA==,type:str]
    VAT_PUBLIC_URL: ENC[AES256_GCM,data:MiBu2tTAI5MJxfEbpow2Hq97VN7Xg6GJR7kC33UC4J+XCPXPHA==,iv:jNBWqFqMjTRFsCIbut3yaJc/fxBpTaK/zsDPuGDNSRo=,tag:A18Pvuwip8rxn+zBjADKmA==,type:str]
    VAT_FRONTEND_URL: ENC[AES256_GCM,data:RKPFxw6IDYR/LFrhf3vvtVVGJJ0ZVKPSjuQwja7lhhxv62PEbA==,iv:RFpnNGF6vnt/oxITPuaYdmigTAke9ndSXEQFgoUi0Xg=,tag:hvilzO/dMf254tgYseO9Bg==,type:str]
    VAT_CORS_ORIGINS: ENC[AES256_GCM,data:KpGagYBFSxGII7hO8jTFE8mvcrqqblivcrtYNjbML3We+Ti8GA==,iv:HVCKJjN0y+T3pNTMf6RIYc1BsJKNL7GRr2tdmyEmCO0=,tag:M9AqbKdOGhfVRSj9Q4H25Q==,type:str]
sops:
    age:
        - recipient: age1h89a67glsx02aqyjd63zvt5vgx7ffaax3v98t4pfm6e5e2pkt43qjw4w4k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBT1FhOFI4UTNCdDRCMndu
            OEY4NHdsdndlZllOQWFEMFJub0lTczJiam00Ckp3Qis0d21PYWczMXozNEIvZTN4
            V3VLQkg0cS9hMmJhYkNTcmZwOVFBNmMKLS0tIGlpcTg1RXN2dkYxT2d2N1MvL1Qv
            MXR2NlhvczFUQThrVzhGai9BUHlqR28KjwjwUvTOmFEC30XIqjoCPasXBhkqHctJ
            OGFBTod9BUHuavnMsOyYojUzs2hA5YOpgu4vGuh8r3AvvbojKcVjcQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-16T19:17:10Z"
    mac: ENC[AES256_GCM,data:G8810pTw3cc1ktIiffHt6ylTLrRkmy2m08NPHrrdN++hwpbUNKCqcDnLX6Wlf7v+uEAQZ1xoR4QqkJDZLgpVV6nb1gtVS6432ok3CjzUEAdVcK7StwAyOxLRuZYsEHBTkVpzat++9YrSdwH/rvG/hZEI4Qkgs8F5a9X2RAV4rdE=,iv:TkCiDCpLXumCpyJIFDVTdYECf6oiYcFhsEBCT0o+EDM=,tag:5NtZLT3rV+hzvF/hY4rJNg==,type:str]
    encrypted_regex: ^(stringData|data)$
    version: 3.12.2
